/**
 * gcp_scope_direnvrc.ts — the shared direnv functions, as data.
 *
 * These live in a `.ts` module rather than a `.sh` sidecar ON PURPOSE: the
 * marketplace vendor step copies `tools/**` filtered to non-test `.ts` files, so
 * a `.sh` next to the CLI is never shipped and `install` would die with ENOENT on
 * exactly the fresh-machine case this tool exists for.
 *
 * Kept as an array of lines so the shell stays readable in review. Single-quoted
 * JS strings throughout — the shell text deliberately contains no single quotes,
 * so nothing here needs escaping.
 *
 * bash-3.2 safe ON PURPOSE: direnv is commonly pinned to the system /bin/bash,
 * and some newer builds deadlock on here-docs. No here-docs, no here-strings,
 * no associative arrays, no ${var,,}, no escaped braces inside ${VAR:-...}.
 */
export const DIRENVRC_FUNCTIONS: string[] = [
  '# Shared direnv functions for per-repo GCP scope.',
  '#',
  '# Managed by gcp_scope.ts — edit the tool, not this block. direnv sources',
  '# direnvrc before every .envrc, so these are available in all of them.',
  '#',
  '# TWO LAYERS, solving different halves of the problem:',
  '#',
  '#   use_gcp_identity <dir>   the ACCOUNT boundary. Flips CLOUDSDK_CONFIG — gcloud’s',
  '#                            whole state dir (credentials.db, the ADC json,',
  '#                            configurations/). Nothing leaks across it. COST: each',
  '#                            dir needs its own login and its own reauth, so use one',
  '#                            per human account, never one per project.',
  '#',
  '#   use_gcp <project> [region] [account]   the PROJECT boundary inside one account.',
  '#                            Named configuration + env overrides. No extra login,',
  '#                            no extra credential store.',
  '',
  'use_gcp_identity() {',
  '    local name="$1"',
  '    if [ -z "$name" ]; then',
  '        log_error "use_gcp_identity: missing config-dir name"',
  '        return 1',
  '    fi',
  '',
  '    export CLOUDSDK_CONFIG="$HOME/.config/gcloud/$name"',
  '    # ADC lives INSIDE the state dir, so an application-default login writes',
  '    # here and nowhere else.',
  '    export GOOGLE_APPLICATION_CREDENTIALS="$CLOUDSDK_CONFIG/application_default_credentials.json"',
  '',
  '    if [ ! -d "$CLOUDSDK_CONFIG" ]; then',
  '        mkdir -p "$CLOUDSDK_CONFIG"',
  '        log_status "gcloud: new identity dir $CLOUDSDK_CONFIG - run gcloud auth login, then gcloud auth application-default login"',
  '    fi',
  '}',
  '',
  '# use_gcp <project> [region] [account]',
  '#',
  '# Scopes the gcloud CLI and every ADC-based client library to <project> for this',
  '# directory tree only. Nothing here is global state — no gcloud config set.',
  '#',
  '#   CLOUDSDK_ACTIVE_CONFIG_NAME  contains a gcloud config set to a per-project',
  '#                                configuration instead of the shared default, and',
  '#                                is where gcloud auth login records the account.',
  '#   CLOUDSDK_CORE_PROJECT        gcloud’s project. Env beats config, so this holds',
  '#                                even if the named configuration does not exist.',
  '#   CLOUDSDK_CORE_ACCOUNT        set ONLY when an account is supplied. There is no',
  '#                                built-in default on purpose: a hardcoded account',
  '#                                breaks every tree on a different gcloud identity,',
  '#                                and the project-only probe cannot see it.',
  '#   GOOGLE_CLOUD_PROJECT         what Go / Node / Python client libs read.',
  '#   GOOGLE_CLOUD_QUOTA_PROJECT   overrides quota_project_id baked into the shared',
  '#   CLOUDSDK_BILLING_QUOTA_PROJECT   ADC json, so an application-default login in',
  '#                                one repo stops re-billing every other repo.',
  '#                                COVERAGE IS NOT TOTAL: cloud.google.com/go/auth,',
  '#                                google.golang.org/api and python google-auth honor',
  '#                                it; golang.org/x/oauth2/google ignores it. Needs',
  '#                                serviceusage.services.use, or 403 USER_PROJECT_DENIED.',
  '#',
  '# GOOGLE_CLOUD_LOCATION is deliberately NOT exported. It is a Vertex model-serving',
  '# location, not a compute region, and preview models exist only on the global',
  '# endpoint — an ambient regional value silently 404s them. Region here means',
  '# CLOUDSDK_COMPUTE_REGION and nothing else.',
  'use_gcp() {',
  '    local project="$1"',
  '    local region="$2"',
  '    local account="$3"',
  '',
  '    if [ -z "$project" ]; then',
  '        log_error "use_gcp: missing project id"',
  '        return 1',
  '    fi',
  '',
  '    # --- gcloud CLI ---',
  '    export CLOUDSDK_ACTIVE_CONFIG_NAME="$project"',
  '    export CLOUDSDK_CORE_PROJECT="$project"',
  '',
  '    # --- ADC client libraries ---',
  '    export GOOGLE_CLOUD_PROJECT="$project"',
  '    export GCP_PROJECT_ID="$project"',
  '    export GOOGLE_CLOUD_QUOTA_PROJECT="$project"',
  '    export CLOUDSDK_BILLING_QUOTA_PROJECT="$project"',
  '',
  '    # Proof-of-execution marker. Only this function sets it, so a checker can',
  '    # tell a real direnv load apart from a CLOUDSDK_CORE_PROJECT that merely',
  '    # leaked in from the calling shell.',
  '    export GCP_SCOPE_ACTIVE="$project"',
  '',
  '    if [ -n "$account" ]; then',
  '        export CLOUDSDK_CORE_ACCOUNT="$account"',
  '    fi',
  '    if [ -n "$region" ]; then',
  '        export CLOUDSDK_COMPUTE_REGION="$region"',
  '    fi',
  '}',
];

/** The functions as a single blob, no trailing newline. */
export function direnvrcFunctions(): string {
  return DIRENVRC_FUNCTIONS.join("\n");
}
