#!/usr/bin/env -S node --experimental-strip-types
/**
 * launchd plist generator for the observability stack.
 *
 * Why this exists: launchd does not inherit interactive PATH, so a
 * hardcoded `/usr/local/bin/node` silently fails to start the ticker on
 * Apple Silicon Homebrew layouts (`/opt/homebrew/bin/node`). The plist
 * sets PATH explicitly to cover both arrangements + manual installs and
 * uses `/usr/bin/env node` to resolve the binary.
 *
 * Phase 1 generates the hostinfo ticker plist. The Phase 7 prune plist
 * is generated by the same helper later — see `--service prune`.
 *
 * Output location:
 *   tools/observability_server/launchd/<label>.plist
 *
 * The plist body is rendered as a literal XML string — no external
 * templating dep — so it's trivial to inspect and unit-test.
 */

import fs from "node:fs";
import path from "node:path";

export interface PlistSpec {
  label: string;
  programArguments: string[];
  /** Tick interval in seconds; only used by the host-ticker service. */
  intervalSeconds?: number;
  /** stdout/stderr log dirs (absolute). Pre-created at 0700. */
  logDir: string;
  /** Working dir (`WorkingDirectory`) for the daemon. */
  workingDir: string;
  /** Extra env. PATH is always set to a portable Homebrew-friendly value. */
  env?: Record<string, string>;
  /** Keep-alive vs run-at-load only. Default: both true. */
  keepAlive?: boolean;
  runAtLoad?: boolean;
}

const PORTABLE_PATH =
  "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/sbin:/usr/sbin:/sbin";

function xmlEscape(raw: string): string {
  return raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function renderPlist(spec: PlistSpec): string {
  const env: Record<string, string> = { PATH: PORTABLE_PATH, ...(spec.env ?? {}) };
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
  );
  lines.push('<plist version="1.0">');
  lines.push("<dict>");
  lines.push("  <key>Label</key>");
  lines.push(`  <string>${xmlEscape(spec.label)}</string>`);
  lines.push("  <key>ProgramArguments</key>");
  lines.push("  <array>");
  for (const a of spec.programArguments) {
    lines.push(`    <string>${xmlEscape(a)}</string>`);
  }
  lines.push("  </array>");
  lines.push("  <key>EnvironmentVariables</key>");
  lines.push("  <dict>");
  for (const [k, v] of Object.entries(env)) {
    lines.push(`    <key>${xmlEscape(k)}</key>`);
    lines.push(`    <string>${xmlEscape(v)}</string>`);
  }
  lines.push("  </dict>");
  lines.push("  <key>WorkingDirectory</key>");
  lines.push(`  <string>${xmlEscape(spec.workingDir)}</string>`);
  lines.push("  <key>StandardOutPath</key>");
  lines.push(
    `  <string>${xmlEscape(path.join(spec.logDir, `${spec.label}.out.log`))}</string>`,
  );
  lines.push("  <key>StandardErrorPath</key>");
  lines.push(
    `  <string>${xmlEscape(path.join(spec.logDir, `${spec.label}.err.log`))}</string>`,
  );
  lines.push("  <key>RunAtLoad</key>");
  lines.push(`  <${spec.runAtLoad === false ? "false" : "true"}/>`);
  lines.push("  <key>KeepAlive</key>");
  lines.push(`  <${spec.keepAlive === false ? "false" : "true"}/>`);
  if (spec.intervalSeconds !== undefined) {
    lines.push("  <key>StartInterval</key>");
    lines.push(`  <integer>${spec.intervalSeconds}</integer>`);
  }
  lines.push("</dict>");
  lines.push("</plist>");
  return lines.join("\n") + "\n";
}

export interface InstallOptions {
  /** Absolute path to the stark-skills repo root. */
  repoRoot: string;
  /** Output directory for plist files. */
  outDir: string;
  /** Log directory (created at 0700 if missing). */
  logDir: string;
  /** Which services to render: "hostinfo" | "prune" | "all". */
  service: "hostinfo" | "prune" | "all";
}

export function buildHostinfoSpec(opts: InstallOptions): PlistSpec {
  return {
    label: "com.aryeh.observability.hostinfo",
    workingDir: opts.repoRoot,
    logDir: opts.logDir,
    programArguments: [
      "/usr/bin/env",
      "node",
      "--experimental-strip-types",
      path.join(opts.repoRoot, "tools", "observability_hostinfo.ts"),
      "--loop",
      "--interval",
      "5s",
    ],
    keepAlive: true,
    runAtLoad: true,
  };
}

export function buildPruneSpec(opts: InstallOptions): PlistSpec {
  // Phase 7 spells out the prune CLI's args. Phase 1 only generates the
  // plist skeleton so the install helper is the single owner of plist
  // shape; Phase 7 wires the actual program arguments through.
  return {
    label: "com.aryeh.observability.prune",
    workingDir: opts.repoRoot,
    logDir: opts.logDir,
    programArguments: [
      "/usr/bin/env",
      "node",
      "--experimental-strip-types",
      path.join(opts.repoRoot, "tools", "observability_prune.ts"),
      "--service",
    ],
    intervalSeconds: 3600,
    keepAlive: false,
    runAtLoad: true,
  };
}

export function install(opts: InstallOptions): string[] {
  fs.mkdirSync(opts.outDir, { recursive: true, mode: 0o755 });
  fs.mkdirSync(opts.logDir, { recursive: true, mode: 0o700 });
  const written: string[] = [];
  const services: Array<"hostinfo" | "prune"> =
    opts.service === "all" ? ["hostinfo", "prune"] : [opts.service];
  for (const s of services) {
    const spec = s === "hostinfo" ? buildHostinfoSpec(opts) : buildPruneSpec(opts);
    const xml = renderPlist(spec);
    const target = path.join(opts.outDir, `${spec.label}.plist`);
    fs.writeFileSync(target, xml, { mode: 0o644 });
    written.push(target);
  }
  return written;
}

function parseArgs(argv: string[]): InstallOptions {
  let repoRoot = process.cwd();
  let outDir: string | undefined;
  let logDir = path.join(
    process.env.HOME ?? "",
    "Library",
    "Logs",
    "stark-observability",
  );
  let service: InstallOptions["service"] = "all";
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--repo-root") {
      repoRoot = argv[++i];
    } else if (a === "--out-dir") {
      outDir = argv[++i];
    } else if (a === "--log-dir") {
      logDir = argv[++i];
    } else if (a === "--service") {
      const v = argv[++i];
      if (v !== "hostinfo" && v !== "prune" && v !== "all") {
        throw new Error(`bad --service: ${v}`);
      }
      service = v;
    } else {
      throw new Error(`unknown arg: ${a}`);
    }
  }
  return {
    repoRoot,
    // Default outDir is computed AFTER the final repoRoot is known so that
    // `--repo-root` actually steers where the plists land. Operators who
    // want a non-default outDir pass `--out-dir` explicitly.
    outDir:
      outDir ?? path.join(repoRoot, "tools", "observability_server", "launchd"),
    logDir,
    service,
  };
}

const isEntry =
  import.meta.url ===
  (process.argv[1]
    ? new URL(`file://${path.resolve(process.argv[1])}`).href
    : "");
if (isEntry) {
  try {
    const opts = parseArgs(process.argv.slice(2));
    const out = install(opts);
    for (const p of out) {
      process.stdout.write(`wrote ${p}\n`);
    }
    process.stdout.write(
      [
        "",
        "Next steps:",
        "  launchctl unload " + path.join(opts.outDir, "com.aryeh.observability.hostinfo.plist") + " 2>/dev/null || true",
        "  launchctl load   " + path.join(opts.outDir, "com.aryeh.observability.hostinfo.plist"),
        "",
      ].join("\n"),
    );
  } catch (err) {
    process.stderr.write(`[install-launchd] ${(err as Error).message}\n`);
    process.exit(1);
  }
}

export const __test = { parseArgs, PORTABLE_PATH };
